# Generated by Django 2.2.3 on 2019-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=53)),
                ('continent', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('surfaceare', models.DecimalField(decimal_places=4, max_digits=10)),
                ('independentyear', models.IntegerField()),
                ('population', models.IntegerField()),
                ('lifeexpectancy', models.DecimalField(decimal_places=3, max_digits=8)),
                ('gnp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gnpld', models.DecimalField(decimal_places=3, max_digits=10)),
                ('localname', models.CharField(max_length=50)),
                ('govname', models.CharField(max_length=45)),
                ('headofstat', models.CharField(max_length=60)),
                ('capital', models.IntegerField()),
                ('code2', models.CharField(max_length=3)),
            ],
        ),
    ]
